.\" Manpage for 301gen.
.\" Contact contact.scottforsberg@gmail.com.
.TH man 8 "07 Jun 2019" ".3" "301gen man page"
.SH NAME
301gen \- create an apache 301 file for a website 
.SH SYNOPSIS
301gen [ -d parameter ] [ -s ]  [ -h ] [ -v ]
.SH DESCRIPTION
This program will create an apache compatible 301 redirects for a website
.SH OPTIONS
-d	domain of new website target

-s	use https for target

-r	redirect to target root

-v 	enables verbose output

-h 	display options
.SH SEE ALSO
301gen --help
.SH BUGS
No known bugs.
.SH AUTHOR
Scott Forsberg (contact.scottforsberg@gmail.com)
